In [1]:
# sum 2 lists 

x = [1,2,3]
y = [5,6,7]
lst=[]
for i in range(len(x)):
    lst.append(x[i]+y[i])
print(lst)

[6, 8, 10]


In [2]:
def add_two_vectors(vect1, vect2):

    lst=[]
    for i in range(len(vect1)):
        assert len(vect1) == len(vect2)
        lst.append(vect1[i]+vect2[i])
    return lst

In [3]:
add_two_vectors([1,2],[1,2])

[2, 4]

In [4]:
# List Comprehension

def add_two_vecs(vect1, vect2):

    assert len(vect1) == len(vect2)
    return [v_i + w_i for v_i, w_i in zip(vect1, vect2)]

assert add_two_vecs([1,2,3], [4,5,6]) == [5,7,9]

In [5]:
add_two_vecs([1,2],[1,2])

[2, 4]

In [6]:
def add_num_to_vect(n, vect2):
    
    lst = []
    
    for i in range(len(vect2)):
        
        lst.append(n+ vect2[i])
    
    return lst


In [7]:
add_num_to_vect(5, [1,2,3])

[6, 7, 8]

In [17]:
# List Comprehension

def add_num(n, vect):
    
    lst = []
    
    return [n + i for i in vect]

# raise an error if the output value is not as expected

assert add_num(5, [1, 2, 3]) == [6, 7, 8]

In [18]:
add_num(5, [1,2,3])

[6, 7, 8]

In [19]:
# List Comprehension

def mul_two_vecs(vect1, vect2):
    
    assert len(vect1) == len(vect2)
    return sum([v_i * w_i for v_i, w_i in zip(vect1, vect2)])

assert mul_two_vecs([1, 2, 3], [4, 5, 6]) == 32

In [20]:
mul_two_vecs([1,2,3],[4,5,6])

32

In [21]:
import numpy as np
 
matrix = np.array([[1, 2, 3],[4, 5, 8],[6, 4, 7]])

matrix.shape

(3, 3)

In [22]:
matrix = [[1, 2, 3],[4, 5, 8],[6, 4, 7]]

rows = len(matrix)

columns = len(matrix[0])

print("The shape of the matrix is ({}, {})".format(rows, columns))

The shape of the matrix is (3, 3)


In [23]:
def shape(A):
    
    rows = len(A)
    
    columns = len(A[0]) if A else 0
    
    return rows, columns

In [26]:
shape([[1,2,3],[2,3,4]])

(2, 3)

In [38]:
def add_two_matr(A,B):
    
    c = [(a_i + b_i) for a_i, b_i in zip(A,B)]
    
    return c

In [39]:
add_two_matr([1,2,3],[4,5,6])

[5, 7, 9]

In [43]:
x = [[1,2,3],[4,5,6]]
y = [[1,2,3],[4,5,6]]

result = [[0,0,0],[0,0,0]]

for i in range(len(x)):
    
    for j in range(len(x[0])):
    
        result[i][j] = x[i][j] + y[i][j]
    
print(result)

[[2, 4, 6], [8, 10, 12]]


In [56]:
# EX:

x = [[1,2,3],[4,5,6]]
y = [[1,2,3],[4,5,6]]



def add_two_matr(a,b):
    
    result = [[0,0,0],[0,0,0]]

    for i in range(len(x)):
    
        for j in range(len(x[0])):
    
            result[i][j] = x[i][j] + y[i][j]
    
    print(result)

In [58]:
import numpy as np
  
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space

entries = list(map(int, input().split()))
  
# For printing the matrix
matrix = np.array(entries).reshape(R, C)

print(matrix)

Enter the number of rows:2
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
1 2 3 4 5 6
[[1 2 3]
 [4 5 6]]


In [55]:
# A basic code for matrix input from user
  
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
# Initialize matrix
matrix = []
print("Enter the entries rowwise:")
  
# For user input
for i in range(R):          # A for loop for row entries
    a =[]
    for j in range(C):      # A for loop for column entries
         a.append(int(input()))
    matrix.append(a)
  
# For printing the matrix
for i in range(R):
    for j in range(C):
        print(matrix[i][j], end = " ")
    print()

Enter the number of rows:2
Enter the number of columns:3
Enter the entries rowwise:
1
2
3
12
2
3
1 2 3 
12 2 3 


In [61]:
import numpy as np
  
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space

A = list(map(int, input().split()))

matrix1 = np.array(A).reshape(R, C)

# ---------------------------------

B = list(map(int, input().split()))

matrix2 = np.array(B).reshape(R, C)

# For printing the matrix

print(matrix1)

print(matrix2)

def add_two_matr(matrix1,matrix2):
    
    c = [(a_i + b_i) for a_i, b_i in zip(matrix1,matrix2)]
    
    return c

add_two_matr(A,B)

Enter the number of rows:2
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
1 2 3 4 5 6
1 2 3 4 5 6
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


[2, 4, 6, 8, 10, 12]

In [65]:
import numpy as np
  
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space

A = list(map(int, input().split()))

matrix1 = np.array(A).reshape(R, C)

# ---------------------------------

B = list(map(int, input().split()))

matrix2 = np.array(B).reshape(R, C)

# For printing the matrix

print(matrix1)

print(matrix2)

def add_two_matr(matrix1,matrix2):
    
    c = [(a_i * b_i) for a_i, b_i in zip(matrix1,matrix2)]
    
    return c

add_two_matr(A,B)

Enter the number of rows:2 
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
1 2 3 4 5 6
4 5 8 6 8 1
[[1 2 3]
 [4 5 6]]
[[4 5 8]
 [6 8 1]]


[4, 10, 24, 24, 40, 6]