In [12]:
import numpy as np

In [13]:
lst = [1,2,3]

arr = np.array(lst)

print(arr, arr.shape, arr.dtype)

[1 2 3] (3,) int32


In [14]:
a = np.empty([3,3])

print(a)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [7.56599128e-307 1.89146896e-307 7.56571288e-307]
 [3.11525958e-307 1.24610723e-306 0.00000000e+000]]


In [29]:
zeros_arr = np.zeros([2,1])
print(zeros_arr)

[[0.]
 [0.]]


In [18]:
ones_array = np.ones([2,1])
print(ones_array)

[[1.]
 [1.]]


In [23]:
# vstack: vertical stack
# hstack: horizontal stack

In [35]:
ones_array = np.ones([2,1])

zeros_arr = np.zeros([2,1])

new_arr = np.vstack((ones_array, zeros_arr))

other_new_arr = np.hstack((ones_array, zeros_arr))

print(new_arr, new_arr.shape,"\n")

print(other_new_arr, other_new_arr.shape)


[[1.]
 [1.]
 [0.]
 [0.]] (4, 1) 

[[1. 0.]
 [1. 0.]] (2, 2)


In [36]:
# indexing & slicing:

# indexing: one element

# slicing: range of elements

In [44]:
# slicing: range of elements

data = np.array([1,2,3,4,5,6])

print(data[:])
print(data[0:1])
print(data[-2:])

[1 2 3 4 5 6]
[1]
[5 6]


In [43]:
# indexing: one element

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((a,b))

print(c)
print(c[1,1])
print(c[1][1])

[[1 2 3]
 [4 5 6]]
5
5


In [45]:
# data splitting

In [127]:
a = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

x, y = a[:,1:], a[:-2,1:]

print(x,"\n")
print(y)

[[2 3]
 [5 6]
 [8 9]] 

[[2 3]]


In [52]:
a = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

split = 2

train, test = a[:split,:], a[split:,:]

print(train, "\n")
print(test)

[[1 2 3]
 [4 5 6]] 

[[7 8 9]]


In [149]:
def train_test_split(data, split_size):
    
    train_data = data[:split_size]
    
    test_data = data[split_size:]
    
    train_labels, train_features = train_data[:,0], train_data[:,1:]
    
    test_labels, test_features = test_data[:,0], test_data[:,1:]
    
    print(np.vstack(train_labels),"\n\n", train_features,"\n")
    print(np.vstack(test_labels),"\n\n", test_features)

data = np.array([["a",1,2,3],
                 ["b",4,5,6],
                 ["c",7,8,9],
                 ["d",1,2,3],
                 ["e",4,5,6],
                 ["f",7,8,9],
                 ["g",1,2,3],
                 ["h",4,5,6],
                 ["i",7,8,9]])

In [150]:
train_test_split(data, len(data)-2)

[['a']
 ['b']
 ['c']
 ['d']
 ['e']
 ['f']
 ['g']] 

 [['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']
 ['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']
 ['1' '2' '3']] 

[['h']
 ['i']] 

 [['4' '5' '6']
 ['7' '8' '9']]


In [146]:
# Array reshape: reshape()

# transfer a matrix with shape (5,) to (1,5)

In [154]:
data = np.array([11,22,33,44,55])

print("data", data)
print("shape", data.shape)

# to make explicitly one row

one_row = data.reshape((1, data.shape[0]))

print("one_row: ", one_row)
print("shape: ", one_row.shape)

one_col = data.reshape((data.shape[0], 1))

print("one_row: \n", one_col)
print("shape: ", one_col.shape)

data [11 22 33 44 55]
shape (5,)
one_row:  [[11 22 33 44 55]]
shape:  (1, 5)
one_row: 
 [[11]
 [22]
 [33]
 [44]
 [55]]
shape:  (5, 1)


In [ ]:
# Numpy array broadcasting

# add and multiply arrays

In [156]:
a = np.array([1,2,3])
print(a)

b = 2

print(b)

c = a + b

print(c)

[1 2 3]
2
[3 4 5]


In [164]:
arr = np.array([[1,2,3],
                [4,5,9]])

print(arr)

d = 2

print(d)

c = arr + d

print(c)

[[1 2 3]
 [4 5 9]]
2
[[ 3  4  5]
 [ 6  7 11]]


In [172]:
arr1 = np.array([[1,2],
                [8,5]])

print(arr,"\n")

arr2 = np.array([[5,1],
              [4,9]])


print(d, "\n")

add = arr1 + arr2

mul = arr1 * arr2

dot_product = arr1.dot(arr2) # multiply each row (R) with each column (C)


print(add, "\n")
print(mul, "\n")
print(dot_product, "\n")

[[1 2 3]
 [4 5 9]] 

[1 2 3] 

[[ 6  3]
 [12 14]] 

[[ 5  2]
 [32 45]] 

[[13 19]
 [60 53]] 



In [169]:
# Note we can add 2 arrays with different number of row 
# but we can't add them if they have differnt number of columns 

In [173]:
# tril & triu

# tril: triangle lower >> takes the bottom left values of the triangle and the rest will be zeros [0]

# triu: triangle upper >> takes the upper right values of the triangle and the rest will be zeros [0]

In [175]:
arr = np.array([[1,2,3],
                [4,5,9],
                [8,10,4]])

lower = np.tril(arr)

print(lower, "\n")

upper = np.triu(arr)

print(upper)

[[ 1  0  0]
 [ 4  5  0]
 [ 8 10  4]] 

[[1 2 3]
 [0 5 9]
 [0 0 4]]


In [176]:
# diag: Diagonal >> takes the matrix diagonal and the left will be zeros [0]

In [178]:
arr = np.array([[1,2,3],
                [4,5,9],
                [8,10,4]])

diagonal = np.diag(arr)

print(diagonal)

[1 5 4]


In [179]:
# diagonal for a list >> will transfer it to a matrix with list values as a diagonal and zeros for the rest of values

list_diag = np.diag(diagonal)

print(list_diag)

[[1 0 0]
 [0 5 0]
 [0 0 4]]


In [180]:
# Identity matrix: is a square matrix with diagonal values equal 1

In [181]:
i = np.identity(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Transpose: (T) >> will transpose the matrix >> leave the diagonal as it is and reverse the upper values with lower values

In [183]:
arr = np.array([[1,2,3],
                [4,5,9],
                [8,10,4]])

transposed_matrix = arr.T

print(transposed_matrix)

[[ 1  4  8]
 [ 2  5 10]
 [ 3  9  4]]


In [187]:
# Task 1



# Inverse Matrix: linalg.inv(array) >> will return the inverse of the matrix

In [188]:
arr = np.array([[1,2,3],
                [4,5,9],
                [8,10,4]])

inverse_matrix = np.linalg.inv(arr)

print(inverse_matrix)

[[-1.66666667  0.52380952  0.07142857]
 [ 1.33333333 -0.47619048  0.07142857]
 [ 0.          0.14285714 -0.07142857]]


In [ ]:
# trace: if a function that return the summation of the matrix [diagonal]

In [186]:
arr = np.array([[1,2,3],
                [4,5,9],
                [8,10,4]])

trace_matrix = np.trace(arr)

print(trace_matrix)

10


In [190]:
# matrix (Determinant): it returns the determinant of the matrix:

# Ex:

# martix = np.array([[1,2],                        
#                    [4,5]])
#


In [195]:
matrix = np.array([[5,2],                        
                   [4,5]])

print(matrix, "\n")

determinant = np.linalg.det(matrix)

print(determinant)

[[5 2]
 [4 5]] 

17.0


In [198]:
# matrix_rank(): is a function that returns the rank of the matrix

# it calculates it from the number of rows that contans non-zero values

# if there is a row that contains zero values it won't be taken into consideration

In [197]:
arr1 = np.array([[5,2,4],                        
                   [4,5,8]])

arr2 = np.array([[5,2,4],                        
                 [0,0,0]])

arr1_rank = np.linalg.matrix_rank(arr1)

arr2_rank = np.linalg.matrix_rank(arr2)

print(arr1_rank)

print(arr2_rank)

2
1


In [203]:
# Sprace Matrix: is matrix with >> number of zeros > numbers of ones

# like: ([[1,1,0],                        
#         [0,0,0]])

# sparcity = number of non-zero element / number of elements

# Dense Matrix:  is matrix with >> number of ones > numbers of zeros

# like: ([[1,1,1],                        
#         [0,1,1]])

In [204]:
# Concepts: used to measure the complixity of any program 

# Space Complixity: consume % from the disk

# Time Complixity: take long time to execute

In [205]:
# SciPy Sparse Matrix:

In [ ]:
# csr_matrix: return the locations that have non-zero value inside the matrix and it's value

In [207]:
# sparce T-Score: csr

from scipy.sparse import csr_matrix

arr = np.array([[1,0,0,1,0,0],                        
                [0,0,2,0,0,1],
                [0,0,0,2,0,0]])

print(arr, "\n")

s = csr_matrix(arr)

print(s, "\n")

to_dense = s.todense()

print(to_dense)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]] 

  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2 

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [211]:
a = np.array([[1,0,0,1,0,0],                        
              [0,0,2,0,0,1],
              [0,0,0,2,0,0]])

In [210]:
# count_nonzero(Matrix): returns the count of non-zero values inside the matrix

np.count_nonzero(a)

5

In [212]:
# size: returns the size of the matrix = number of rows [R] * number of columns [C] 

a.size

18

In [213]:
# calc_sparsity(matrix)

def calc_sparsity(a):
    
    return 1.0 - np.count_nonzero(a) / a.size

a = np.array([[1,0,0,1,0,0],                        
              [0,0,2,0,0,1],
              [0,0,0,2,0,0]])

print(calc_sparsity(a))

0.7222222222222222


In [241]:
def calc_spars(a):
    
    count = 0
    
    for x in a:
        
        for j in x:
        
            if j == 0:
            
                count += 1
    
    rows = len(a)
    
    cols = len(a[0])
    
    size = rows*cols
        
    spars = count / size
    

    return ("""The numbers of elements in the matrix is {} and the size of the matrix is {}, then the sparse will be equal {}""".format(count, size, spars))

a = np.array([[1,0,0,1,0,0],                        
              [0,0,2,0,0,1],
              [0,0,0,2,0,0]])

print(calc_spars(a))    

The numbers of elements in the matrix is 13 and the size of the matrix is 18, then the sparse will be equal 0.7222222222222222
